### ISSUE TITLE
Add-on auto opens/refreshes a video from homepage when hover preview starts playing

### ISSUE THREAD

**Issue by TheAfroOfDoom** [nilssonk/force-youtube-theme-refresh#1]
first off just wanna say i appreciate this extension idea - the new youtube layout sucks balls

---

however if you hover over a video and the preview starts playing (the silent thumbnail GIF) this extension "auto-clicks" on that video and refreshes the page. this is very jarring especially since you don't even need to actually click anything for it to forcibly take you to a video

**Comment by nilssonk** [comment]
Thank you for the feedback! I will take a look at it this week but cannot guarantee a fix. It's all just a huge hack at the moment.
