### ISSUE TITLE
Auto-refresh forcefully redirects off of (non-youtube) websites that have a youtube vid embed

### ISSUE THREAD

**Issue by TheAfroOfDoom** [nilssonk/force-youtube-theme-refresh#14]
Sample: https://www.lourdes.edu/

the embed is on the 2nd dot (out of 6) of the little slideshow thing at the top of the page; inspecting reveals it as an embed

![image](https://github.com/nilssonk/force-youtube-theme-refresh/assets/13565346/72a4cd10-d38a-48f5-a0bf-dd2b4c8cbf9e)

![image](https://github.com/nilssonk/force-youtube-theme-refresh/assets/13565346/b755845f-13a3-410d-91e0-f1373beef7de)

**Comment by nilssonk** [comment]
Thank you for the report! I will take a look at this ASAP, but life is sort of busy at the moment. I haven't really dealt with iframes properly so this is next on the list.

**Comment by nilssonk** [comment]
The fix was unexpectedly easy (I think). Version 1.0.4 is now pending on addons.mozilla.org.

Please try it out and reopen this issue in case there are still problems.
